import Utils from "./Utils";
import GPS from "./GPS";
import WIFI from "./WIFI";
import System from "./System";
import Update from "./Update";
import Hotspot from "./Hotspot";
import Mobile from "./Mobile";
import IOS from "./IOS";
export { GPS, WIFI, Utils, System, Update, Hotspot, Mobile, IOS };
export default { GPS, WIFI, Utils, System, Update, Hotspot, Mobile, IOS };
